### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by mateusbsouza** [esm-ispm-unibe-ch/cinema#8]
Hi, hope you are alright. Thank you very much for the tool!

I would like to report an error

I was doing my analysis and an error started to appear after I clicked on "set up your evaluation". Then I tried with my other databases that had already worked and the error also appeared. Then I tried with the dataset demo and the error persisted.

Best regards
![photo_2021-08-06_09-28-28](https://user-images.githubusercontent.com/88542756/128512366-fd5a4cec-3a99-4ff9-ac30-94d2359533dd.jpg)

**Comment by mateusbsouza** [comment]
Up

**Comment by mateusbsouza** [comment]
Started working again!

**Comment by mateusbsouza** [comment]
The same problem came back

**Comment by FFFWH** [comment]
I have encountered the same problem. How can I solve it?

**Comment by evanderFC** [comment]
problem again
